"""Distill a public-safe narrative profile from a brand's raw call transcripts.

This runs ONCE per refresh (the expensive transcript read), turning ~tens of KB of
calls into a compact, reusable profile that every post generation then reads — so
the transcript cost is amortised. Crucially, the raw transcripts live in
``_sources/`` which generation is firewalled from; only this step reads them, and
it emits PUBLIC-SAFE output (confidential internals excluded).
"""

from __future__ import annotations

from dataclasses import dataclass, field

from marketing_engine.harness.prompts import (
    DISTILL_SYSTEM,
    build_distill_prompt,
)
from marketing_engine.content.postprocess import extract_json_obj
from marketing_engine.content.strategy import STRATEGY_FILE, STRATEGY_SECTIONS, render_strategy_md
from marketing_engine.sdk.client import AgentRunOptions
from marketing_engine.sdk.models import resolve_model

SOURCE_EXTS = {".txt", ".md", ".markdown"}
MAX_SOURCE_CHARS = 150_000  # cap the single distillation call


class DistillError(Exception):
    pass


@dataclass
class DistillResult:
    core_narrative: str
    trajectory: str
    key_ideas: list[str] = field(default_factory=list)
    proof_points: list[str] = field(default_factory=list)
    avoid: list[str] = field(default_factory=list)
    # The three universal filter dimensions (STRATEGY_SECTIONS).
    strategy: dict[str, list[str]] = field(default_factory=dict)
    files_written: list[str] = field(default_factory=list)
    model: str | None = None
    usage: dict = field(default_factory=dict)


def _read_sources(layout, tenant_id: str, brand_id: str) -> str:
    sdir = layout.sources_dir(tenant_id, brand_id)
    if not sdir.is_dir():
        return ""
    chunks: list[str] = []
    total = 0
    for path in sorted(sdir.glob("*")):
        if path.suffix.lower() not in SOURCE_EXTS or not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="replace").strip()
        if not text:
            continue
        chunks.append(f"### {path.name}\n{text}")
        total += len(text)
        if total >= MAX_SOURCE_CHARS:
            break
    return "\n\n".join(chunks)[:MAX_SOURCE_CHARS]


def _bullets(items) -> str:
    return "\n".join(f"- {str(x).strip()}" for x in (items or []) if str(x).strip())


async def distill(engine, tenant_id: str, brand_id: str) -> DistillResult:
    """Read ``_sources/`` and write the distilled profile. Raises ``DistillError``
    if there are no sources or the model returns no usable JSON."""

    tenant = engine.registry.get_tenant(tenant_id)
    brand = engine.registry.get_brand(tenant_id, brand_id)
    layout = engine.layout

    sources = _read_sources(layout, tenant_id, brand_id)
    if not sources.strip():
        raise DistillError(
            f"No sources in {layout.sources_dir(tenant_id, brand_id)} — add transcripts first."
        )

    model = resolve_model(
        "editor",
        brand_models=brand.models.model_dump(),
        tenant_default=tenant.default_model,
        settings_default=engine.settings.default_model,
    )
    options = AgentRunOptions(
        system_prompt=DISTILL_SYSTEM,
        cwd=layout.brand_dir(tenant_id, brand_id),
        allowed_tools=[],  # transcripts are inlined; no file reading
        model=model,
    )
    result = await engine.llm.run(build_distill_prompt(sources), options)
    data = extract_json_obj(result.text)
    if not data or not (data.get("core_narrative") or data.get("key_ideas")):
        raise DistillError("Distillation returned no usable profile — try again.")

    core = str(data.get("core_narrative", "")).strip()
    traj = str(data.get("trajectory", "")).strip()
    ideas = data.get("key_ideas") or []
    proofs = data.get("proof_points") or []
    avoid = data.get("avoid") or []
    # The three universal filter dimensions, pulled by their schema keys.
    strategy = {
        sec.key: list(data.get(sec.key) or []) for sec in STRATEGY_SECTIONS
    }

    written: list[str] = []

    # One auto file holds the whole distilled strategy: the three filter
    # dimensions + the angle menu + direction + avoid. render_strategy_md keeps
    # a fixed, identical layout for every brand.
    spath = layout.rules_dir(tenant_id, brand_id) / STRATEGY_FILE
    spath.parent.mkdir(parents=True, exist_ok=True)
    spath.write_text(render_strategy_md(data), encoding="utf-8")
    written.append(f"_rules/{STRATEGY_FILE}")

    # Migrate away from the old filename so the vault doesn't keep a stale dupe.
    old = layout.rules_dir(tenant_id, brand_id) / "key-ideas.md"
    if old.is_file():
        old.unlink()

    if proofs:
        ppath = layout.kb_dir(tenant_id, brand_id) / "proof-points.md"
        ppath.parent.mkdir(parents=True, exist_ok=True)
        ppath.write_text(
            "# Proof points — auto-generated by `engine distill`. Public-safe; verify before use.\n\n"
            + _bullets(proofs)
            + "\n",
            encoding="utf-8",
        )
        written.append("_kb/proof-points.md")

    return DistillResult(
        core_narrative=core,
        trajectory=traj,
        key_ideas=list(ideas),
        proof_points=list(proofs),
        avoid=list(avoid),
        strategy=strategy,
        files_written=written,
        model=result.model,
        usage=result.usage,
    )
