"""The universal strategy schema — the agnostic core of the content filter.

Every brand, whoever they are, is described by the SAME set of strategy sections.
``distill`` fills them from that brand's own uploaded calls; ``filter`` scores
ideas against them. The engine never hard-codes a brand — it only knows these
section *names*. Any client is simply one fill of this template; upload another
company's material and the same code fills the same sections with their answers.

One source of truth (``STRATEGY_SECTIONS``) is imported by both the distiller
(which writes the sections) and the filter (which reads them), so the two can
never drift apart.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class StrategySection:
    key: str  # the JSON key distill emits and the filter reads
    label: str  # the heading shown in _rules/strategy.md
    instruction: str  # what the LLM should put here (used in the distill prompt)


# The three dimensions the filter scores every idea against. Deliberately
# business-generic so they apply to any company that uploads data.
STRATEGY_SECTIONS: list[StrategySection] = [
    StrategySection(
        "business_principles",
        "BUSINESS PRINCIPLES",
        "the durable truths of how this business creates and protects value — its "
        "model, product mechanics, and what makes it credible/trustworthy",
    ),
    StrategySection(
        "customer_personas",
        "CUSTOMER PERSONAS",
        "who the content speaks to: their situation and what they care about (it is "
        "fine for this to be broad)",
    ),
    StrategySection(
        "customer_narratives",
        "CUSTOMER NARRATIVES",
        "the customer's felt story in their own words: the pains, doubts, and hopes a "
        "post can speak to",
    ),
]

# Auto-file the distiller writes and the filter + assembler read.
STRATEGY_FILE = "strategy.md"

STRATEGY_BANNER = (
    "# Strategy profile — auto-generated by `engine distill`.\n"
    "# PUBLIC-SAFE. You may hand-edit to correct it; re-running distill overwrites it.\n"
    "# The filter scores every post idea against the BUSINESS PRINCIPLES,\n"
    "# CUSTOMER PERSONAS, and CUSTOMER NARRATIVES below.\n"
)


def _bullets(items) -> str:
    return "\n".join(f"- {str(x).strip()}" for x in (items or []) if str(x).strip())


def render_strategy_md(data: dict) -> str:
    """Render the distilled ``data`` dict into the human-editable strategy.md.

    Sections come out in a fixed order so the file looks the same for every brand.
    The three filter dimensions first, then the angle menu / direction / avoid.
    """

    parts = [STRATEGY_BANNER]
    for sec in STRATEGY_SECTIONS:
        body = _bullets(data.get(sec.key))
        if body:
            parts += [f"## {sec.label}", "", body, ""]
    if data.get("key_ideas"):
        parts += [
            "## KEY IDEAS (each short post develops ONE, tied to a principle + narrative)",
            "",
            _bullets(data.get("key_ideas")),
            "",
        ]
    if str(data.get("trajectory", "")).strip():
        parts += ["## STRATEGIC DIRECTION", "", str(data["trajectory"]).strip(), ""]
    if data.get("avoid"):
        parts += ["## AVOID (surfaced in calls)", "", _bullets(data.get("avoid")), ""]
    return "\n".join(parts).strip() + "\n"


def parse_strategy_md(text: str) -> dict[str, list[str]]:
    """Parse strategy.md back into ``{section_key: [bullets]}`` for the filter.

    Tolerant of hand-edits: it matches on the section *label*, collects the ``-``
    bullets under each ``## LABEL`` until the next heading, and ignores anything
    else. Returns only the keys it actually found (missing sections are absent).
    """

    by_label = {sec.label.upper(): sec.key for sec in STRATEGY_SECTIONS}
    out: dict[str, list[str]] = {}
    current: str | None = None
    for raw in (text or "").splitlines():
        line = raw.strip()
        if line.startswith("#"):
            heading = line.lstrip("#").strip().upper()
            # Match a section even if the heading has a trailing parenthetical.
            current = next(
                (key for lbl, key in by_label.items() if heading.startswith(lbl)), None
            )
            continue
        if current and line.startswith("-"):
            item = line.lstrip("-").strip()
            if item:
                out.setdefault(current, []).append(item)
    return out


def load_strategy(layout, tenant_id: str, brand_id: str) -> dict[str, list[str]]:
    """Read the brand's distilled strategy from the vault. Empty dict if none yet
    (so a brand with no distilled strategy still generates — just unfiltered)."""

    path = layout.rules_dir(tenant_id, brand_id) / STRATEGY_FILE
    if not path.is_file():
        return {}
    return parse_strategy_md(path.read_text(encoding="utf-8"))


def format_strategy_for_filter(strategy: dict[str, list[str]]) -> str:
    """Render the filter's view of the strategy: the three scored dimensions."""

    parts: list[str] = []
    for sec in STRATEGY_SECTIONS:
        items = strategy.get(sec.key)
        if items:
            parts.append(f"## {sec.label}")
            parts.append(_bullets(items))
            parts.append("")
    return "\n".join(parts).strip()


def has_filter_dimensions(strategy: dict[str, list[str]]) -> bool:
    """True if we have enough to filter on: at least principles AND narratives."""

    return bool(strategy.get("business_principles")) and bool(
        strategy.get("customer_narratives")
    )
