"""The news scraper — the News input from the systems diagram.

Runs a Claude agent with web tools (WebSearch + WebFetch) over the user's Claude
Code login (no API key) to find RECENT, relevant news for a brand, judges each
story through the brand's distilled strategy (the same business-principle ×
customer-narrative lens the content filter uses), and writes a relevance-filtered,
public-safe digest into ``_kb/news/<date>.md`` — which generation may then read.

Agnostic: the agent derives its own searches from the brand's identity + strategy
(seed queries in ``brand.yaml: news.queries`` are optional). A brand works because
its strategy is filled in; any other brand works the same way.

The model RETURNS structured JSON; the engine writes the file deterministically —
so a flaky/partial agent run can't half-write the vault. Brand-isolated (the
``_sources`` firewall still applies); fails soft (no items -> nothing written).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone

from marketing_engine.content.strategy import format_strategy_for_filter, load_strategy
from marketing_engine.harness.prompts import SCRAPE_SYSTEM, build_scrape_prompt
from marketing_engine.sdk.client import AgentRunOptions
from marketing_engine.sdk.models import SONNET

_RELEVANCE_RANK = {"high": 3, "medium": 2, "med": 2, "low": 1, "": 0}


@dataclass
class NewsItem:
    title: str
    url: str = ""
    source: str = ""
    date: str = ""
    summary: str = ""
    principle: str = ""
    narrative: str = ""
    angle: str = ""
    relevance: str = ""

    def as_dict(self) -> dict:
        return self.__dict__.copy()


@dataclass
class ScrapeResult:
    items: list[NewsItem] = field(default_factory=list)
    file_written: str | None = None
    model: str | None = None
    usage: dict = field(default_factory=dict)
    denied_paths: list[str] = field(default_factory=list)


def _today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _coerce_items(raw: list, max_items: int, min_relevance: str = "medium") -> list[NewsItem]:
    floor = _RELEVANCE_RANK.get(min_relevance, 2)
    out: list[NewsItem] = []
    for it in raw:
        if not isinstance(it, dict):
            continue
        title = str(it.get("title", "")).strip()
        if not title:
            continue
        rel = str(it.get("relevance", "")).strip().lower()
        if _RELEVANCE_RANK.get(rel, 0) < floor:
            continue
        out.append(
            NewsItem(
                title=title,
                url=str(it.get("url", "")).strip(),
                source=str(it.get("source", "")).strip(),
                date=str(it.get("date", "")).strip(),
                summary=str(it.get("summary", "")).strip(),
                principle=str(it.get("principle", "")).strip(),
                narrative=str(it.get("narrative", "")).strip(),
                angle=str(it.get("angle", "")).strip(),
                relevance=rel,
            )
        )
    out.sort(key=lambda i: _RELEVANCE_RANK.get(i.relevance, 0), reverse=True)
    return out[:max_items]


def _render_digest(items: list[NewsItem], date_str: str) -> str:
    lines = [
        f"# News digest — {date_str} (auto-generated by `engine scrape`).",
        "# Relevance-filtered + public-safe. Each item is tied to a business",
        "# principle / customer narrative. Generation may cite these.",
        "",
    ]
    for it in items:
        lines.append(f"## {it.title}")
        meta = " · ".join(p for p in [it.source, it.date, it.relevance] if p)
        if meta:
            lines.append(f"*{meta}*")
        if it.url:
            lines.append(it.url)
        if it.summary:
            lines += ["", it.summary]
        tags = " · ".join(p for p in [it.principle, it.narrative] if p)
        if tags:
            lines.append(f"\n**Ties to:** {tags}")
        if it.angle:
            lines.append(f"**Possible angle:** {it.angle}")
        lines.append("")
    return "\n".join(lines).strip() + "\n"


async def scrape_news(
    engine,
    tenant_id: str,
    brand_id: str,
    *,
    max_items: int | None = None,
    queries: list[str] | None = None,
    date_str: str | None = None,
    write: bool = True,
) -> ScrapeResult:
    """Search the web for relevant news, filter through the brand strategy, and
    write a digest to ``_kb/news/<date>.md``. Returns a :class:`ScrapeResult`."""

    tenant = engine.registry.get_tenant(tenant_id)
    brand = engine.registry.get_brand(tenant_id, brand_id)
    layout = engine.layout
    date_str = date_str or _today()

    news_cfg = getattr(brand, "news", None)
    max_items = max_items or (getattr(news_cfg, "max_items", None) or 8)
    lookback = getattr(news_cfg, "lookback_days", None) or 30
    seeds = queries if queries is not None else list(getattr(news_cfg, "queries", []) or [])

    strategy = load_strategy(layout, tenant_id, brand_id)
    strategy_block = format_strategy_for_filter(strategy)

    model = (
        getattr(brand.models, "news", None) or brand.models.default or SONNET
    )
    denied: list[str] = []
    options = AgentRunOptions(
        system_prompt=SCRAPE_SYSTEM
        + ("\n\n## BRAND IDENTITY\n" + brand.identity if brand.identity else ""),
        cwd=layout.brand_dir(tenant_id, brand_id),
        add_dirs=[layout.shared_dir],
        allowed_roots=list(layout.allowed_roots(tenant_id, brand_id)),
        denied_roots=[layout.sources_dir(tenant_id, brand_id)],  # firewall stays on
        allowed_tools=["WebSearch", "WebFetch"],  # research only; engine does the write
        model=model,
    )
    prompt = build_scrape_prompt(
        brand_identity=brand.identity,
        strategy_block=strategy_block,
        queries=seeds,
        max_items=max_items,
        today=date_str,
        lookback_days=lookback,
    )
    result = await engine.llm.run(prompt, options)
    # Items are JSON objects, so parse the array directly (extract_json_list would
    # flatten each object to a string).
    items = _coerce_items(_raw_objects(result.text) or [], max_items)

    file_written = None
    if write and items:
        ndir = layout.news_dir(tenant_id, brand_id)
        ndir.mkdir(parents=True, exist_ok=True)
        path = ndir / f"{date_str}.md"
        path.write_text(_render_digest(items, date_str), encoding="utf-8")
        file_written = f"_kb/news/{date_str}.md"

    return ScrapeResult(
        items=items,
        file_written=file_written,
        model=result.model,
        usage=result.usage,
        denied_paths=result.denied_paths,
    )


def latest_news_headlines(layout, tenant_id: str, brand_id: str, *, limit: int = 6) -> list[str]:
    """Return recent news headlines (+ angle) from the newest digest in _kb/news/.

    Used to seed News-related ideas during idea generation. Empty list if there's
    no news yet — so the feature degrades cleanly before the first scrape."""

    ndir = layout.news_dir(tenant_id, brand_id)
    if not ndir.is_dir():
        return []
    files = sorted(ndir.glob("*.md"), reverse=True)  # newest date first
    if not files:
        return []
    out: list[str] = []
    title: str | None = None
    for line in files[0].read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s.startswith("## "):
            title = s[3:].strip()
            out.append(title)
        elif s.startswith("**Possible angle:**") and title:
            out[-1] = f"{title} — {s.removeprefix('**Possible angle:**').strip()}"
        if len(out) >= limit and not s.startswith("**Possible angle:**"):
            break
    return out[:limit]


def _raw_objects(text: str) -> list:
    """Parse a JSON array of objects from a model reply (tolerates preamble/fences)."""

    import json

    if not text:
        return []
    start = text.find("[")
    if start < 0:
        return []
    depth = 0
    for i in range(start, len(text)):
        ch = text[i]
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                try:
                    data = json.loads(text[start : i + 1])
                except Exception:
                    return []
                return data if isinstance(data, list) else []
    return []
