"""The news scraper — the News input from the systems diagram.

Runs a Claude agent with web tools (WebSearch + WebFetch) over the user's Claude
Code login (no API key) to find RECENT, relevant news for a brand, judges each
story through the brand's distilled strategy (the same business-principle ×
customer-narrative lens the content filter uses), and writes a relevance-filtered,
public-safe digest into ``_kb/news/<date>.md`` — which generation may then read.

Agnostic: the agent derives its own searches from the brand's identity + strategy
(seed queries in ``brand.yaml: news.queries`` are optional). Denario works because
its strategy is filled in; any other brand works the same way.

The model RETURNS structured JSON; the engine writes the file deterministically —
so a flaky/partial agent run can't half-write the vault. Brand-isolated (the
``_sources`` firewall still applies); fails soft (no items -> nothing written).
"""

from __future__ import annotations

import asyncio
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from email.utils import parsedate_to_datetime
from typing import NamedTuple

from marketing_engine.content.strategy import format_strategy_for_filter, load_strategy
from marketing_engine.harness.prompts import (
    CROSS_EXAM_SYSTEM,
    SCRAPE_SYSTEM,
    build_cross_exam_prompt,
    build_scrape_prompt,
)
from marketing_engine.sdk.client import AgentRunOptions
from marketing_engine.sdk.models import SONNET

_RELEVANCE_RANK = {"high": 3, "medium": 2, "med": 2, "low": 1, "": 0}


@dataclass
class NewsItem:
    title: str
    url: str = ""
    source: str = ""
    date: str = ""
    summary: str = ""
    principle: str = ""
    narrative: str = ""
    angle: str = ""
    relevance: str = ""
    # Post-ready fields (make an item a drop-in seed for the short-post + image
    # templates, not just a headline). All optional so a brand that doesn't fill
    # them in still works exactly as before.
    cluster: str = ""       # the strategy theme/cluster this maps to
    stat: str = ""          # a featurable number + unit (→ stat card), e.g. "49%"
    quote: str = ""         # a short pull-quote (→ quote card)
    product_tie: str = ""   # the concrete tie to the brand's product/offering
    template: str = ""      # suggested image template: stat | quote | headline
    corroboration: str = "" # independent sources that confirmed the core stat/claim

    def as_dict(self) -> dict:
        return self.__dict__.copy()


@dataclass
class ScrapeResult:
    items: list[NewsItem] = field(default_factory=list)
    file_written: str | None = None
    model: str | None = None
    usage: dict = field(default_factory=dict)
    denied_paths: list[str] = field(default_factory=list)
    verified: bool = False  # did the adversarial fact-check pass actually run?
    dropped: list[dict] = field(default_factory=list)  # items the verifier rejected + why
    coverage: dict = field(default_factory=dict)  # {category: {lang: count}} from the scan
    candidate_count: int = 0  # how many fresh candidates the scan surfaced pre-filter


def _today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _coerce_items(raw: list, max_items: int, min_relevance: str = "medium") -> list[NewsItem]:
    floor = _RELEVANCE_RANK.get(min_relevance, 2)
    out: list[NewsItem] = []
    for it in raw:
        if not isinstance(it, dict):
            continue
        title = str(it.get("title", "")).strip()
        if not title:
            continue
        rel = str(it.get("relevance", "")).strip().lower()
        if _RELEVANCE_RANK.get(rel, 0) < floor:
            continue
        template = str(it.get("template", "")).strip().lower()
        if template not in {"stat", "quote", "headline"}:
            template = ""
        out.append(
            NewsItem(
                title=title,
                url=str(it.get("url", "")).strip(),
                source=str(it.get("source", "")).strip(),
                date=str(it.get("date", "")).strip(),
                summary=str(it.get("summary", "")).strip(),
                principle=str(it.get("principle", "")).strip(),
                narrative=str(it.get("narrative", "")).strip(),
                angle=str(it.get("angle", "")).strip(),
                relevance=rel,
                cluster=str(it.get("cluster", "")).strip(),
                stat=str(it.get("stat", "")).strip(),
                quote=str(it.get("quote", "")).strip(),
                product_tie=str(it.get("product_tie", "")).strip(),
                template=template,
            )
        )
    out.sort(key=lambda i: _RELEVANCE_RANK.get(i.relevance, 0), reverse=True)
    return out[:max_items]


def _render_digest(items: list[NewsItem], date_str: str) -> str:
    lines = [
        f"# News digest — {date_str} (auto-generated by `engine scrape`).",
        "# Scanned from Google News, filtered for Swiss-saver relevance + source reliability,",
        "# then cross-examined: each core stat/claim below was confirmed across independent",
        "# reputable sources. Each ties to a business principle / customer narrative.",
        "",
    ]
    for it in items:
        lines.append(f"## {it.title}")
        meta = " · ".join(p for p in [it.source, it.date, it.relevance] if p)
        if meta:
            lines.append(f"*{meta}*")
        if it.url:
            lines.append(it.url)
        if it.summary:
            lines += ["", it.summary]
        tags = " · ".join(p for p in [it.principle, it.narrative] if p)
        if tags:
            lines.append(f"\n**Ties to:** {tags}")
        if it.angle:
            lines.append(f"**Possible angle:** {it.angle}")
        # Post-ready seed line: which cluster + which image template + the concrete
        # stat/quote to feature, so generation can render a card straight from this.
        seed = " → ".join(p for p in [it.cluster, f"{it.template} card" if it.template else ""] if p)
        if seed:
            lines.append(f"**Post seed:** {seed}")
        if it.stat:
            lines.append(f"**Featured stat:** {it.stat}")
        if it.quote:
            lines.append(f"**Pull-quote:** “{it.quote}”")
        if it.product_tie:
            lines.append(f"**Product hook:** {it.product_tie}")
        if it.corroboration:
            lines.append(f"**Confirmed by:** {it.corroboration}")
        lines.append("")
    return "\n".join(lines).strip() + "\n"


# -- Step 1: deterministic MULTI-SURFACE, MULTI-LOCALE news scan -----------------
# Coverage is a function of a TAXONOMY x LOCALES x SURFACES, not a hand-kept keyword
# list. Google News RSS is the universal adapter (real dates + outlet names); we scan
# it in every Swiss language (de/fr/it — Switzerland is trilingual) plus English for
# the global metals story, and can also pull direct primary-source / outlet RSS feeds.
# All plain Python: no model, no token cost, fail-soft (a dead feed contributes nothing).
class _Locale(NamedTuple):
    hl: str
    gl: str
    ceid: str
    lang: str


_CH_LOCALES = [
    _Locale("de-CH", "CH", "CH:de", "de"),
    _Locale("fr-CH", "CH", "CH:fr", "fr"),
    _Locale("it-CH", "CH", "CH:it", "it"),
    _Locale("en-US", "US", "US:en", "en"),
]

_LOCALE_BY_CODE: dict[str, _Locale] = {}
for _loc in _CH_LOCALES:  # accept either "de-CH" or "de" in config
    _LOCALE_BY_CODE[_loc.hl] = _loc
    _LOCALE_BY_CODE[_loc.lang] = _loc


def _locales_from_config(codes) -> list[_Locale] | None:
    """Map config locale codes (e.g. ``["de-CH","fr-CH","en"]``) to ``_Locale`` objects;
    ``None`` (unset/empty) means the scanner uses the full trilingual+en default."""
    if not codes:
        return None
    out = [_LOCALE_BY_CODE[str(c)] for c in codes if str(c) in _LOCALE_BY_CODE]
    return out or None


def _gnews_url(query: str, loc: _Locale) -> str:
    q = urllib.parse.quote(query)
    return f"https://news.google.com/rss/search?q={q}&hl={loc.hl}&gl={loc.gl}&ceid={loc.ceid}"


def _fetch_rss_items(url: str, default_source: str = "", timeout: int = 20) -> list[dict]:
    """Fetch + parse ONE RSS feed (Google News OR a plain outlet/primary feed) into
    ``{title,url,source,date,ts}`` dicts. ``ts`` is the parsed ``pubDate`` (tz-aware) used
    for the freshness cut; ``date`` is the ``YYYY-MM-DD`` display string. The outlet name
    comes from the item's ``<source>`` (Google News), else the feed's channel title, else
    ``default_source``. Any network/parse error -> ``[]`` (fail-soft)."""

    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        data = urllib.request.urlopen(req, timeout=timeout).read()
        root = ET.fromstring(data)
    except Exception:
        return []
    chan = root.find("channel")
    chan_title = ((chan.findtext("title") if chan is not None else "") or "").strip()
    out: list[dict] = []
    for it in root.findall(".//item"):
        title = (it.findtext("title") or "").strip()
        if not title:
            continue
        link = (it.findtext("link") or "").strip()
        src_el = it.find("{*}source")
        source = (src_el.text or "").strip() if (src_el is not None and src_el.text) else ""
        if not source:
            source = default_source or chan_title
        # Google News often appends " - Outlet" to the title; strip it when we have a source.
        if source and title.endswith(f" - {source}"):
            title = title[: -len(f" - {source}")].strip()
        pub = (it.findtext("pubDate") or "").strip()
        ts = None
        if pub:
            try:
                ts = parsedate_to_datetime(pub)
                if ts.tzinfo is None:
                    ts = ts.replace(tzinfo=timezone.utc)
            except Exception:
                ts = None
        out.append(
            {
                "title": title,
                "url": link,
                "source": source,
                "date": ts.strftime("%Y-%m-%d") if ts else "",
                "ts": ts,
            }
        )
    return out


def build_query_matrix(topics) -> list[dict]:
    """Expand a categorised topic taxonomy into ordered scan entries — so coverage is a
    property of the taxonomy, not a flat hand-list.

    ``topics`` maps a category to per-language query lists, e.g.
    ``{"home-lockout": {"de": [...], "fr": [...]}}``. A category may instead map to a flat
    list, treated as language-agnostic (``lang="any"`` → run in every locale; good for
    proper nouns like "UBS"). Returns ordered ``{category, lang, query}`` entries; the
    order is the priority/coverage order the scanner fills and caps against."""

    entries: list[dict] = []
    for category, spec in (topics or {}).items():
        if isinstance(spec, dict):
            for lang, qs in spec.items():
                for q in qs or []:
                    if str(q).strip():
                        entries.append({"category": category, "lang": str(lang), "query": str(q).strip()})
        elif isinstance(spec, (list, tuple)):
            for q in spec:
                if str(q).strip():
                    entries.append({"category": category, "lang": "any", "query": str(q).strip()})
    return entries


async def scan_news_matrix(
    entries: list[dict],
    *,
    locales: list[_Locale] | None = None,
    feeds: list[dict] | None = None,
    lookback_days: int,
    per_query: int = 5,
    max_candidates: int = 48,
) -> tuple[list[dict], dict]:
    """Multi-surface, multi-locale scan. For each matrix ``entry`` (``{query,lang,category}``)
    scan Google News in the matching Swiss-language locale (or every locale when
    ``lang="any"``); additionally pull any direct RSS ``feeds`` (primary sources / outlets).
    Returns ``(candidates, coverage)`` where ``coverage`` is ``{category: {lang: count}}`` so
    empty cells (no live news on a topic in a language) are VISIBLE, never silent.

    Entry ORDER is the priority order: the pool is filled entry-by-entry and capped, so a
    high-frequency beat can't crowd a slower one out. Deterministic and fail-soft."""

    locales = list(locales) if locales else list(_CH_LOCALES)
    by_lang = {loc.lang: loc for loc in locales}
    cutoff = datetime.now(timezone.utc) - timedelta(days=lookback_days)

    # Build the fetch plan: (group_index, category, lang_label, url, default_source).
    specs: list[tuple[int, str, str, str, str]] = []
    for i, e in enumerate(entries or []):
        q = str(e.get("query", "")).strip()
        if not q:
            continue
        lang = str(e.get("lang", "any") or "any")
        cat = str(e.get("category", ""))
        locs = locales if lang == "any" else ([by_lang[lang]] if lang in by_lang else [])
        for loc in locs:
            specs.append((i, cat, loc.lang, _gnews_url(q, loc), ""))
    feed_base = (max((s[0] for s in specs), default=-1)) + 1
    for j, f in enumerate(feeds or []):
        url = str((f or {}).get("url", "")).strip()
        if url:
            specs.append((feed_base + j, str(f.get("category", "")), "feed", url, str(f.get("source", "")).strip()))

    if not specs:
        return [], {}

    raws = await asyncio.gather(
        *(asyncio.to_thread(_fetch_rss_items, url, ds) for (_i, _c, _l, url, ds) in specs)
    )

    # Group in-window items by their group index; tally coverage by category x language.
    groups: dict[int, dict] = {}
    coverage: dict = {}
    for (i, cat, lang, _url, _ds), items in zip(specs, raws):
        g = groups.setdefault(i, {"items": []})
        n = 0
        for it in items:
            if it["ts"] is None or it["ts"] < cutoff:  # in-window only; undated dropped
                continue
            g["items"].append(it)
            n += 1
        cov = coverage.setdefault(cat or "(uncategorised)", {})
        cov[lang] = cov.get(lang, 0) + n

    out: list[dict] = []
    seen: set[str] = set()
    for i in sorted(groups):  # entry/priority order preserved
        bucket = sorted(groups[i]["items"], key=lambda x: x["ts"], reverse=True)
        kept = 0
        for it in bucket:
            key = it["title"].lower()
            if key in seen:
                continue
            seen.add(key)
            out.append({k: it[k] for k in ("title", "url", "source", "date")})
            kept += 1
            if kept >= per_query or len(out) >= max_candidates:
                break
        if len(out) >= max_candidates:
            break
    return out, coverage


async def google_news_scan(
    queries: list[str],
    *,
    lookback_days: int,
    per_query: int = 5,
    max_candidates: int = 40,
    locales: list[_Locale] | None = None,
) -> list[dict]:
    """Backward-compatible flat-query entry point: scan a plain keyword list across the
    given (or default trilingual+en) locales and return just the candidate pool. Thin
    wrapper over :func:`scan_news_matrix` (each query runs as a language-agnostic entry)."""

    entries = [{"category": "", "lang": "any", "query": q} for q in (queries or [])]
    candidates, _coverage = await scan_news_matrix(
        entries, locales=locales, feeds=None, lookback_days=lookback_days,
        per_query=per_query, max_candidates=max_candidates,
    )
    return candidates


async def scrape_news(
    engine,
    tenant_id: str,
    brand_id: str,
    *,
    max_items: int | None = None,
    queries: list[str] | None = None,
    date_str: str | None = None,
    write: bool = True,
    verify: bool | None = None,
    lookback_days: int | None = None,
) -> ScrapeResult:
    """Search the web for relevant news, filter through the brand strategy, and
    write a digest to ``_kb/news/<date>.md``. Returns a :class:`ScrapeResult`."""

    tenant = engine.registry.get_tenant(tenant_id)
    brand = engine.registry.get_brand(tenant_id, brand_id)
    layout = engine.layout
    date_str = date_str or _today()

    news_cfg = getattr(brand, "news", None)
    max_items = max_items or (getattr(news_cfg, "max_items", None) or 8)
    lookback = lookback_days or getattr(news_cfg, "lookback_days", None) or 30
    seeds = queries if queries is not None else list(getattr(news_cfg, "queries", []) or [])
    do_verify = getattr(news_cfg, "verify", True) if verify is None else verify
    reputable_only = getattr(news_cfg, "reputable_only", True)

    strategy = load_strategy(layout, tenant_id, brand_id)
    strategy_block = format_strategy_for_filter(strategy)

    model = (
        getattr(brand.models, "news", None) or brand.models.default or SONNET
    )
    options = AgentRunOptions(
        system_prompt=SCRAPE_SYSTEM
        + ("\n\n## BRAND IDENTITY\n" + brand.identity if brand.identity else ""),
        cwd=layout.brand_dir(tenant_id, brand_id),
        add_dirs=[layout.shared_dir],
        allowed_roots=list(layout.allowed_roots(tenant_id, brand_id)),
        denied_roots=[layout.sources_dir(tenant_id, brand_id)],  # firewall stays on
        allowed_tools=["WebSearch", "WebFetch"],  # read candidates; engine does the write
        model=model,
    )

    # STEP 1 — deterministic MULTI-SURFACE, MULTI-LOCALE scan driven by the query matrix.
    # Coverage is a property of the taxonomy x locales x surfaces, not a flat keyword list.
    topics = getattr(news_cfg, "topics", None) or {}
    locales = _locales_from_config(getattr(news_cfg, "locales", None))
    feeds = list(getattr(news_cfg, "feeds", []) or [])
    if queries is not None:  # explicit CLI override → flat, language-agnostic
        entries = [{"category": "", "lang": "any", "query": q} for q in queries]
    elif topics:  # the generated matrix (categorised, trilingual)
        entries = build_query_matrix(topics)
    else:  # legacy flat query list
        entries = [{"category": "", "lang": "any", "query": q} for q in seeds]
    candidates, coverage = await scan_news_matrix(
        entries, locales=locales, feeds=feeds, lookback_days=lookback
    )
    if not candidates:  # nothing fresh on the wire this run → fail soft, write nothing
        return ScrapeResult(items=[], model=model, denied_paths=[], coverage=coverage)

    # STEPS 2-3 — the scout FILTERS that pool for Denario-relevance-for-Swiss-savers and
    # source reliability (it selects + shapes from the pool; it does not invent items).
    prompt = build_scrape_prompt(
        brand_identity=brand.identity,
        strategy_block=strategy_block,
        queries=seeds,
        max_items=max_items,
        today=date_str,
        lookback_days=lookback,
        focus=getattr(news_cfg, "focus", "") or "",
        exclude=list(getattr(news_cfg, "exclude", []) or []),
        preferred_sources=list(getattr(news_cfg, "preferred_sources", []) or []),
        candidates=candidates,
    )
    result = await engine.llm.run(prompt, options)
    # Items are JSON objects, so parse the array directly (extract_json_list would
    # flatten each object to a string).
    items = _coerce_items(_raw_objects(result.text) or [], max_items)

    # STEP 4 — cross-examination: corroborate each kept item's core stat/claim across
    # INDEPENDENT reputable sources (not just the one cited page). Anything that cannot be
    # confirmed elsewhere, or is from a non-reputable outlet, is dropped with a reason.
    verified = False
    dropped: list[dict] = []
    if do_verify and items:
        items, dropped, verified = await cross_examine_items(
            engine,
            tenant_id,
            brand_id,
            items,
            date_str=date_str,
            lookback_days=lookback,
            reputable_only=reputable_only,
        )

    file_written = None
    if write and items:
        ndir = layout.news_dir(tenant_id, brand_id)
        ndir.mkdir(parents=True, exist_ok=True)
        path = ndir / f"{date_str}.md"
        path.write_text(_render_digest(items, date_str), encoding="utf-8")
        file_written = f"_kb/news/{date_str}.md"

    return ScrapeResult(
        items=items,
        file_written=file_written,
        model=result.model,
        usage=result.usage,
        denied_paths=result.denied_paths,
        verified=verified,
        dropped=dropped,
        coverage=coverage,
        candidate_count=len(candidates),
    )


async def _cross_examine_one(engine, options, item: NewsItem, *, date_str: str, lookback_days: int,
                             reputable_only: bool) -> dict | None:
    """Run ONE cross-examination subagent; return its verdict dict, or ``None`` if the
    subagent errored or returned nothing parseable (so the caller can tell a real verdict
    apart from an infrastructure miss)."""

    prompt = build_cross_exam_prompt(
        item, today=date_str, lookback_days=lookback_days, reputable_only=reputable_only
    )
    try:
        result = await engine.llm.run(prompt, options)
    except Exception:
        return None
    return _raw_object(result.text) or None


async def cross_examine_items(
    engine,
    tenant_id: str,
    brand_id: str,
    items: list[NewsItem],
    *,
    date_str: str,
    lookback_days: int,
    reputable_only: bool = True,
) -> tuple[list[NewsItem], list[dict], bool]:
    """Step 4 — cross-examination pass over the filtered items.

    Fans out ONE subagent PER item (run concurrently). Each does NOT merely re-open the
    cited page: it independently CORROBORATES the item's core stat/claim across at least
    two OTHER independent reputable sources, and returns ``corroborated`` (confirmed by
    >=2 independent reputable sources), ``legitimate`` (the original outlet is citable),
    the confirming ``sources``, and a corrected summary/date. Isolating each item means one
    shaky claim can't colour the verdicts on the others. Returns ``(kept, dropped, ran)``:

    - ``kept`` — items corroborated across independent sources (corrections + corroboration
      applied), still ranked.
    - ``dropped`` — ``{title, reason}`` for each rejected item, so nothing vanishes silently.
    - ``ran`` — True if at least one subagent returned a usable verdict. If EVERY subagent
      errors/returns nothing (an infra miss, not a real rejection), we DON'T silently empty
      the digest: ``ran`` is False and the caller keeps the un-cross-examined items.
    """

    if not items:
        return [], [], False

    brand = engine.registry.get_brand(tenant_id, brand_id)
    layout = engine.layout
    model = getattr(brand.models, "news", None) or brand.models.default or SONNET
    options = AgentRunOptions(
        system_prompt=CROSS_EXAM_SYSTEM,
        cwd=layout.brand_dir(tenant_id, brand_id),
        add_dirs=[layout.shared_dir],
        allowed_roots=list(layout.allowed_roots(tenant_id, brand_id)),
        denied_roots=[layout.sources_dir(tenant_id, brand_id)],  # firewall stays on
        allowed_tools=["WebSearch", "WebFetch"],  # corroborate across sources; no writing
        model=model,
    )

    verdicts = await asyncio.gather(
        *(
            _cross_examine_one(
                engine, options, it,
                date_str=date_str, lookback_days=lookback_days, reputable_only=reputable_only,
            )
            for it in items
        )
    )
    if all(v is None for v in verdicts):
        # No subagent produced a verdict (agent error / unparseable across the board).
        # Fail OPEN so a flaky pass can't wipe a good scrape — but flag it un-verified.
        return items, [], False

    kept: list[NewsItem] = []
    dropped: list[dict] = []
    for it, v in zip(items, verdicts):
        if v is None:
            dropped.append({"title": it.title, "reason": "no verdict returned — dropped to be safe"})
            continue
        corroborated = bool(v.get("corroborated"))
        legitimate = bool(v.get("legitimate"))
        reason = str(v.get("reason", "")).strip()
        if not corroborated:
            dropped.append({"title": it.title, "reason": reason or "not corroborated by independent sources"})
            continue
        if reputable_only and not legitimate:
            dropped.append({"title": it.title, "reason": reason or "source not reputable"})
            continue
        # Corroborated — apply corrections + record the independent confirming sources.
        corrected_summary = str(v.get("summary", "")).strip()
        if corrected_summary:
            it.summary = corrected_summary
        corrected_date = str(v.get("date", "")).strip()
        if corrected_date:
            it.date = corrected_date
        srcs = v.get("sources")
        if isinstance(srcs, list):
            it.corroboration = ", ".join(str(s).strip() for s in srcs if str(s).strip())[:300]
        kept.append(it)
    return kept, dropped, True


def latest_news_headlines(layout, tenant_id: str, brand_id: str, *, limit: int = 6) -> list[str]:
    """Return recent news headlines (+ angle) from the newest digest in _kb/news/.

    Used to seed News-related ideas during idea generation. Empty list if there's
    no news yet — so the feature degrades cleanly before the first scrape."""

    ndir = layout.news_dir(tenant_id, brand_id)
    if not ndir.is_dir():
        return []
    files = sorted(ndir.glob("*.md"), reverse=True)  # newest date first
    if not files:
        return []
    out: list[str] = []
    title: str | None = None
    for line in files[0].read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s.startswith("## "):
            title = s[3:].strip()
            out.append(title)
        elif s.startswith("**Possible angle:**") and title:
            out[-1] = f"{title} — {s.removeprefix('**Possible angle:**').strip()}"
        if len(out) >= limit and not s.startswith("**Possible angle:**"):
            break
    return out[:limit]


def load_evergreen_concepts(layout, tenant_id: str, brand_id: str, *, limit: int = 14) -> list[str]:
    """Return always-on post-idea seeds from the brand's ``_kb/concepts.md``.

    Evergreen concepts (e.g. tax facts, product truths) don't expire the way news
    does, so the news scraper's lookback window would drop them. This reads a simple
    human-maintained markdown file — every bullet (``- ``/``* ``) line is one concept
    — and hands them to idea generation alongside the fresh news headlines.

    Agnostic and fail-soft: no file -> empty list, so the feature degrades cleanly
    for any brand that hasn't written a concept bank."""

    path = layout.kb_dir(tenant_id, brand_id) / "concepts.md"
    if not path.is_file():
        return []
    out: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s.startswith(("- ", "* ")):
            concept = s[2:].strip().lstrip("*").strip()  # drop bullet + any bold markers
            if concept:
                out.append(concept)
        if len(out) >= limit:
            break
    return out[:limit]


def _raw_object(text: str) -> dict:
    """Parse the first balanced JSON object from a model reply (tolerates preamble/fences).

    Used for the per-item verifier, which returns a single ``{legitimate, accurate, …}``
    verdict object rather than an array."""

    import json

    if not text:
        return {}
    start = text.find("{")
    if start < 0:
        return {}
    depth = 0
    for i in range(start, len(text)):
        ch = text[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                try:
                    data = json.loads(text[start : i + 1])
                except Exception:
                    return {}
                return data if isinstance(data, dict) else {}
    return {}


def _raw_objects(text: str) -> list:
    """Parse a JSON array of objects from a model reply (tolerates preamble/fences)."""

    import json

    if not text:
        return []
    start = text.find("[")
    if start < 0:
        return []
    depth = 0
    for i in range(start, len(text)):
        ch = text[i]
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                try:
                    data = json.loads(text[start : i + 1])
                except Exception:
                    return []
                return data if isinstance(data, list) else []
    return []
